name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3

